defaults:
  - default
  - _self_

# ===================
# ====== basic ======
# ===================
parallel: "worker" # "single" or "host" or "worker"
sync_mode: "async"  # "async", "sync"
save_path: '/mnt/huangke1/logs/worker'
avd_name: 'test_Android'
save_images: False

# ===================
# ====== path =======
# ===================
android_avd_home: '/mnt/huangke1/.android/avd'
emulator_path: '/mnt/huangke1/.android/emulator/emulator'
adb_path: '/mnt/huangke1/.android/platform-tools/adb'
cache_dir: '/mnt/huangke1/.cache'
assets_path: '/mnt/huangke1/carl_distrl/assets/task_set'

# ===================
# ====== algo =======
# ===================
policy_lm: '/mnt/huangke1/auto-UI/cooelf/Auto-UI/Auto-UI-Base'
critic_lm: '/mnt/huangke1/auto-UI/roberta-base'

# ===================
# ===== collect =====
# ===================
collect_iterations: 10
bsize: 4 # number of emulators parallelly on the machine
rollout_size: 4 # how many trajectories to collect between training iterations (should be multiple of bsize)

# ===================
# ====== eval =======
# ===================
eval_iterations: 1000
